stages:
  - test
  - build
  - deploy

test-job1:
  stage: test
  image: python:latest
  script:
    - pip install -r requirements.txt
    - cd cicd
    - python manage.py test web

build-image:
  stage: build
  only:
    - tags
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:dind
      command: ["--insecure-registry=${CI_REGISTRY}"]
  script:
    - docker build -t "${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}" .
    - docker push "${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"

deploy-job:
  stage: deploy
  only:
    - tags
  image: bitnami/kubectl
  script:
    - sed -i "s/____CI_COMMIT_TAG____/${CI_COMMIT_TAG}/g" deployment.yaml
    - cat deployment.yaml
    - kubectl apply -f deployment.yaml
    - kubectl apply -f service.yaml