stages:
  - test
  - build
  - staging
  - deploy

test-job1:
  stage: test
  image: python:latest
  script:
    - pip install -r requirements.txt
    - cd cicd
    - python manage.py test web

build-image:
  stage: build
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:dind
      command: ["--insecure-registry=${CI_REGISTRY}"]
  script:
    - ls
    - docker info
    - docker build -t "${CI_REGISTRY}/${CI_PROJECT_NAME}" .
    - docker push "${CI_REGISTRY}/${CI_PROJECT_NAME}"
