stages:
  - test
  - build
  - staging
  - deploy

test-job1:
  stage: test
  image: python:latest
  script:
    - python --version

build-image:
  stage: build
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry", "${CI_REGISTRY}"]
  script:
    - docker info
    - docker build -t "10.41.8.200:30200/${CI_PROJECT_NAME}" .
    - docker push "10.41.8.200:30200/${CI_PROJECT_NAME}"
