stages:
  - build
  - test

test-job1:
  stage: test
  script:
    - "test start"
    - "test done"

test-job2:
  stage: test
  script:
    - echo $CI_REGISTRY
    - docker info 

build-image:
  stage: build
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlaby
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker info
