stages:
  - test
  - build
  - staging
  - deploy

test-job1:
  stage: test
  image: python:latest
  script:
    - python --version

build-image:
  stage: build
  only:
    - tags
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:dind
    command: ["--insecure-registry=${CI_REGISTRY}"]
  script:
    - docker build -t "${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}" .
    - docker push "${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"
