image: docker:stable

stages:
  - build
  - test

test-job1:
  stage: test
  script:
    - "test start"
    - "test done"

test-job2:
  stage: test
  script:
    - echo $CI_REGISTRY

build-job1:
  stage: build
  script:
    - echo "build start"
    - echo "build done"
