stages:
  - build
  - test

image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375/

services:
  - docker:dind
  
before_script:
  - docker info

test-job1:
  stage: test
  script:
    - "test start"
    - "test done"

test-job2:
  stage: test
  script:
    - echo $CI_REGISTRY
    - docker info 

build-image:
  stage: build
  script:
    - docker info
