stages:
  - test
  - build

test-job1:
  stage: test
  script:
    - echo ${CI_REGISTRY}
    - echo ${CI_REGISTRY_IMAGE}
    - echo ${CI_COMMIT_TAG}
    -echo ${CI_COMMIT_REF_NAME}

test-job2:
  stage: test
  script:
    - echo 2

build-image:
  stage: build
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:dind
  script:
    - docker pull 10.41.8.200:30200/cicd-test
