stages:
  - build
  - test

test-job1:
  stage: test
  script:
    - "test start"
    - "test done"

test-job2:
  stage: test
  script:
    - echo $CI_REGISTRY
    - docker info 

build-image:
  stage: build
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: unix:///var/run/docker.sock
  services:
    - name: docker:dind
      command: ["--insecure-registry=10.41.8.200:30200"]
  script:
    - docker pull 10.41.8.200:30200/cicd-test
    - docker images inspect 10.41.8.200:30200/cicd-test | head
